[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.19'
no_match_path = "*/fork/*"
evm_version = "shanghai"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.fork]
no_match_path = ""
match_path = "*/fork/*"


unknown_chain = { key = "d6t6nsi75237SaUxle2VLWC9UY1yxZyh", chain = 1, url = "https://virtual.mainnet.rpc.tenderly.co/b06086f4-872d-4dd5-ad1c-e3478f4574a4" }
